// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaM1NbJL8oBv4I3zIUXIptY4nkCh9WgDE',
    appId: '1:418806878741:web:ee21d6f3a3651ae148341c',
    messagingSenderId: '418806878741',
    projectId: 'fir-flutter-codelab-e6309',
    authDomain: 'fir-flutter-codelab-e6309.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-e6309.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVcMk_rkuKVgtJvhsONTNLqgSSBM0ePBI',
    appId: '1:418806878741:android:1eeecf7fa6de1b4648341c',
    messagingSenderId: '418806878741',
    projectId: 'fir-flutter-codelab-e6309',
    storageBucket: 'fir-flutter-codelab-e6309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWqM99zCDZmx4TaJkz6Ri2ihME33WfWb8',
    appId: '1:418806878741:ios:9ff7e62bf01c08f448341c',
    messagingSenderId: '418806878741',
    projectId: 'fir-flutter-codelab-e6309',
    storageBucket: 'fir-flutter-codelab-e6309.appspot.com',
    iosClientId: '418806878741-ma2qt3n30alkfd5rj5td8j8d1s0tkrf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWqM99zCDZmx4TaJkz6Ri2ihME33WfWb8',
    appId: '1:418806878741:ios:9ff7e62bf01c08f448341c',
    messagingSenderId: '418806878741',
    projectId: 'fir-flutter-codelab-e6309',
    storageBucket: 'fir-flutter-codelab-e6309.appspot.com',
    iosClientId: '418806878741-ma2qt3n30alkfd5rj5td8j8d1s0tkrf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
